name: Keep Render App Awake

on:
  schedule:
    - cron: "*/15 * * * *" # Every 15 minutes
  workflow_dispatch: # Optional: allows manual runs

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -I https://your-app-name.onrender.com/